Catch problems during compilation and translation phase

diff --git a/hornix b/hornix
--- a/hornix
+++ b/hornix
@@ -45,11 +45,11 @@ echo "(set-logic HORN)" > $filename.smt2
 
 $DIR/bin/clang-18 -Xclang -disable-O0-optnone -S -emit-llvm $fullname -o $filename.ll 2>/dev/null
 if [[ ! -e "${filename}.ll" || ! -s "${filename}.ll" ]]; then
-  echo "error"
+  echo "UNKNOWN: Error during initial compilation"
   exit 1
 fi
 $DIR/bin/opt -passes=mem2reg -S $filename.ll -o $filename.ll
-$DIR/bin/opt -disable-output $filename.ll -passes=chc-transform >> $filename.smt2
+$DIR/bin/opt -disable-output $filename.ll -passes=chc-transform >> $filename.smt2 2>/dev/null || { echo  "UNKNOWN: Error during translation to CHC!"; exit 1; } 
 
 echo "(check-sat)" >> $filename.smt2
 PATH="${DIR}/bin":${PATH}
