Run translation pass in a subshell
This prevents reporting an error message when the command aborts.

diff --git a/hornix b/hornix
--- a/hornix
+++ b/hornix
@@ -49,7 +49,7 @@ if [[ ! -e "${filename}.ll" || ! -s "${filename}.ll" ]]; then
   exit 1
 fi
 $DIR/bin/opt -passes=mem2reg -S $filename.ll -o $filename.ll
-$DIR/bin/opt -disable-output $filename.ll -passes=chc-transform >> $filename.smt2 2>/dev/null || { echo  "UNKNOWN: Error during translation to CHC!"; exit 1; } 
+$($DIR/bin/opt -disable-output $filename.ll -passes=chc-transform >> $filename.smt2 2>/dev/null) || { echo  "UNKNOWN: Error during translation to CHC!"; exit 1; }
 
 echo "(check-sat)" >> $filename.smt2
 PATH="${DIR}/bin":${PATH}
